### ISSUE TITLE
Crash when using ViewPropTypes/TextPropTypes

### ISSUE THREAD

**Issue by pe1ros** [lukebrandonfarrell/react-native-screen-keyboard#20]
Hi ! 

I have PR for fox issue, that crash app, when we using ViewPropTypes for Styles in PropTypes
![Screenshot 2022-10-27 at 10 50 52](https://user-images.githubusercontent.com/58532915/198278118-a3cc2e7a-2efc-4529-9386-520e1bcd64a7.png)

**Comment by lukebrandonfarrell** [comment]
@pe1ros Could you open your PR, and then we can review it? Thanks!

**Comment by pe1ros** [comment]
@lukebrandonfarrell Hello!

I haven't permissions for this (

**Comment by lukebrandonfarrell** [comment]
@pe1ros You shouldn't need permissions to create a PR to public repository, fork the repo, make the changes and open a pull request from your forked repo to this one. Let me know if that makes sense!
